// export const initialObjectState = {
//   as: "",
//   asname: "",
//   callingCode: "",
//   city: "",
//   continent: "",
//   continentCode: "",
//   country: "",
//   countryCode: "",
//   countryCode3: "",
//   currency: "",
//   currentTime: "",
//   district: "",
//   hosting: false,
//   isp: "",
//   lat: null,
//   lon: null,
//   mobile: false,
//   offset: null,
//   org: "",
//   proxy: false,
//   query: "",
//   region: "",
//   regionName: "",
//   reverse: "",
//   status: "",
//   timezone: "",
//   zip: "",
// };

import { useState } from "react";

// export const finalObjectState = {
//   as: location.as,
//   asname: location.asname,
//   callingCode: location.callingCode,
//   city: location.city,
//   continent: location.continent,
//   continentCode: location.continentCode,
//   country: location.country,
//   countryCode: location.countryCode,
//   countryCode3: location.countryCode3,
//   currency: location.currency,
//   currentTime: location.currentTime,
//   district: location.district,
//   hosting: location.hosting,
//   isp: location.isp,
//   lat: location.lat,
//   lon: location.lon,
//   mobile: location.mobile,
//   offset: location.offset,
//   org: location.org,
//   proxy: location.proxy,
//   query: location.query,
//   region: location.region,
//   regionName: location.regionName,
//   reverse: location.reverse,
//   status: location.status,
//   timezone: location.timezone,
//   zip: location.zip,
// };
